train:
  eeg_root: D:/Neuroinformatics_research_2025/Oddball/ds116_eeg
  fmri_root: D:/Neuroinformatics_research_2025/Oddball/ds000116
  a424_label_nii: D:/Neuroinformatics_research_2025/BrainLM/A424_resampled_to_bold.nii.gz
  cbramod_weights: D:/Neuroinformatics_research_2025/MNI_templates/CBraMod/pretrained_weights/pretrained_weights.pth
  brainlm_model_dir: D:/Neuroinformatics_research_2025/MNI_templates/BrainLM/pretrained_models/2023-06-06-22_15_00-checkpoint-1400
  output_dir: D:/Neuroinformatics_research_2025/Multi_modal_NTM/translator_runs
  device: cuda
  seed: 42
  epochs: 20
  batch_size: 16
  lr: 0.0001
  weight_decay: 0.0001
  window_sec: 40
  stride_sec: 10
  num_workers: 0
  amp: false
  debug: false
  fmri_norm: zscore
  wandb_project: Neural_translation_august10
  wandb_run_name: oddball_Neural_translation_run3_aug10_data_split
  wandb_off: false
  eeg_loss_w: 1.0
  fmri_loss_w: 1.0
  eeg_seconds_per_token: 40
  resume: null

  # fixed subject splits (anchors so test reuses these)
  train_subjects: &train_subjects [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  val_subjects:   &val_subjects   [13]
  test_subjects:  &test_subjects  [14, 15, 17]

test:
  eeg_root: D:/Neuroinformatics_research_2025/Oddball/ds116_eeg
  fmri_root: D:/Neuroinformatics_research_2025/Oddball/ds000116
  a424_label_nii: D:/Neuroinformatics_research_2025/BrainLM/A424_resampled_to_bold.nii.gz
  cbramod_weights: D:/Neuroinformatics_research_2025/MNI_templates/CBraMod/pretrained_weights/pretrained_weights.pth
  brainlm_model_dir: D:/Neuroinformatics_research_2025/MNI_templates/BrainLM/pretrained_models/2023-06-06-22_15_00-checkpoint-1400
  checkpoint: translator_runs/translator_best.pt
  device: cuda
  seed: 42
  fmri_norm: zscore
  window_sec: 40
  original_fs: 1000
  target_fs: 200
  stride_sec: 10
  channels_limit: 34
  batch_size: 8
  num_workers: 0
  eeg_seconds_per_token: 40
  mode: both
  partial_visible_frac: 0.5
  save_recons: null
  save_n_batches: 0

  # reuse IDs from train via aliases
  train_subjects: *train_subjects
  val_subjects:   *val_subjects
  test_subjects:  *test_subjects
